---
- name: Redhat | Install libselinux-python
  yum:
    name: libselinux-python

- name: Redhat | Update sysconfig
  lineinfile: dest=/etc/sysconfig/network line="HOSTNAME={{ fqdn }}" regexp="HOSTNAME="
